name: install docker action

description: install docker and docker-compose in ubuntu machines

inputs:
  ssh_host:
    description: remote host address
    required: true

  ssh_user:
    description: remote host user
    required: true

  ssh_key:
    description: ssh private key
    required: true

  reboot_time:
    default: 60
    description: time in seconds necessary for the remote host to completely reboot

runs:
  using: composite
  steps:
    - name: Install docker and docker-compose
      uses: darklabsbr/ssh-action@v1.1
      with:
        ssh_host: ${{ inputs.ssh_host }}
        ssh_user: ${{ inputs.ssh_user }}
        ssh_key: ${{ inputs.ssh_key }}
        command: |
          if ! which docker; then
            export DEBIAN_FRONTEND=noninteractive

            sudo apt-get update -y
            sudo apt-get install \
                ca-certificates \
                curl \
                gnupg \
                lsb-release -y

            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor --batch --yes -o /usr/share/keyrings/docker-archive-keyring.gpg

            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

            sudo apt-get update -y
            sudo apt-get install docker-ce docker-ce-cli containerd.io -y
            sudo groupadd docker
            sudo usermod -aG docker $USER

            docker --version

            touch /tmp/install_docker_action

            echo "Reboot the system to complete the docker installation."
          else
            echo "Docker already installed. No system reboot is needed."
          fi

          if ! which docker-compose; then
            export DEBIAN_FRONTEND=noninteractive

            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

            docker-compose --version
          fi

    - name: Check if reboot is needed
      id: check_reboot
      uses: darklabsbr/ssh-action@v1.1
      with:
        ssh_host: ${{ inputs.ssh_host }}
        ssh_user: ${{ inputs.ssh_user }}
        ssh_key: ${{ inputs.ssh_key }}
        command: echo "$(ls /tmp | grep -i install_docker_action)"

    - name: Reboot the server if necessary
      if: steps.check_reboot.outputs.output == 'install_docker_action'
      uses: darklabsbr/ssh-action@v1.1
      with:
        ssh_host: ${{ inputs.ssh_host }}
        ssh_user: ${{ inputs.ssh_user }}
        ssh_key: ${{ inputs.ssh_key }}
        command: sudo reboot

    - name: Wait server reboot if necessary
      if: steps.check_reboot.outputs.output == 'install_docker_action'
      shell: bash
      run: sleep ${{ inputs.reboot_time }}s
